version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: "main"
    labels: ["dependabot"]
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "com.google.firebase:firebase-messaging"
    commit-message:
      prefix: "chore"
