name: "Build and Test"
on: [push, pull_request]
jobs:
  unit-tests:
    name: "Unit Tests"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{github.head_ref}}
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Run Unit Tests"
        run: ./gradlew test
      - name: "Print Android Unit Tests Report"
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
      - name: "Archive Unit Test Results"
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: "unit-tests-results"
          path: ./**/build/reports/**
  lint-checks:
    name: "Lint Checks"
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Run Lint"
        run: ./gradlew lint
      - name: "Archive Lint Test Results"
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: "lint-results"
          path: ./**/build/reports/**
  kotlin-lint-checks:
    name: "Kotlin Lint Checks"
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Run Android Core SDK Kotlin Lint"
        run: ./gradlew ktlintCheck
      - name: "Archive Kotlin Lint Test Results"
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: "kotlin-lint-results"
          path: ./**/build/reports/**
